[build]
  command = "next build && next export"
  publish = "out"
  functions = ".netlify/functions"

[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
from = "/blog/"
to = "/"

[[redirects]]
from = "/news/"
to = "/"

[[redirects]]
from = "/news/tidal-fluid-power/"
to = "/"
